### ISSUE TITLE
Wrong vertical position

### ISSUE THREAD

**Issue by iOS-altima** [AlexLittlejohn/ALThreeCircleSpinner#5]
Hello!
Thank you for your code!
You should replace line 100 with this code:
            circle.frame = CGRectMake(CGFloat(i) * 3 * offset, size.height / 2 - offset, circleSize, circleSize);

key change - "size.height / 2 - offset"
In this case dots will be centered vertically correctly.

**Comment by AlexLittlejohn** [comment]
Thank you for pointing this out. I have committed a fix for it now
